### ISSUE TITLE
Nested Comments

### ISSUE THREAD

**Issue by MatthewPageCS** [hughesjeff/CSCapstone#11]
Extend your CommentsApp to allow nested comments, similar to what you might find on Facebook, Youtube, and Reddit. Users should not only be able to leave a comment in the thread, but also reply to other users comments as a sub-comment.

This will require:
* Modifying your comment model to support nested comments
* Modifying your addComment logic to support nested comments.
* Modifying your comments.html template to correctly display nested comments. You will also need to create a method for the user to reply to any comment. This can be accomplished with many <form> elements, or using Javascript to cleverly render a reply form and indicate what comment is parent.

**Comment by MatthewPageCS** [comment]
Nonono, we're leaving this as a todo. It'll be the last thing I do, if anything at all, but it's staying as an issue :p

**Comment by hughesjeff** [comment]
We don't have time.
