### ISSUE TITLE
Matching System

### ISSUE THREAD

**Issue by MatthewPageCS** [hughesjeff/CSCapstone#9]
* Implement a group -> project matching system.
* Your system should intelligently suggest projects which fit the combined student properties of each group.

**Comment by MatthewPageCS** [comment]
I still think the best way for us to do this is to have a long list of check boxes for the user, and for the project. Therefore we need no parsing of input.

**Comment by hughesjeff** [comment]
This should be done on the front page of the site.

**Comment by MatthewPageCS** [comment]
in-class, gustavo suggested that we do it on the page where we assign a project.

**Comment by hughesjeff** [comment]
Okay, we could do it there.
